[project]
name = "seminario1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "psycopg2-binary>=2.9.11",
    "uvicorn>=0.38.0",
]
